### ISSUE TITLE
Blank page in the BiB microsoft window

### ISSUE THREAD

**Issue by par-retest** [waelmas/frameless-bitb#4] opened 2024-02-15 12:17 UTC
Hi!

First, thanks for your impressive work.

Very recently (less than a week ago), the browser-in-browser window stopped working upon changing pages: the "enter username" page works properly, but as soon as someone enters their login and validates, tries to go back, or does anything, the BiB page becomes blank.

Since minimizing it and clicking on "login with microsoft" shows the next page, it seems that it could be a re-drawing issue?
Indeed, commenting this [clearInterval](https://github.com/waelmas/frameless-bitb/blob/main/pages/secondary/script.js#L87) makes things work again until the KMSI page, which simply doesn't appear.
It can be fixed by changing https://github.com/waelmas/frameless-bitb/blob/main/pages/secondary/script.js#L6 to login/common, but this all seems like hotfixes that don't address the deeper root cause.

Maybe Microsoft changed some things on their end?

**Comment by waelmas** [comment] 2024-02-15 17:15
Hey,

Thanks for reporting this and looking into the root cause.

I managed to replicate it too. It seems to happen only when the password page is branded (company logos etc) which seems to execute some kind of state reset or it removes the win-scroll element and injects it again (still investigating).

The clearInterval trick makes sense based on the above assumptions, but indeed it's more of a hotfix with potential side effects.

Looking now into adding some kind state change detection and/or mounting/unmounting of the win-scroll element to trigger the JS logic in those cases too.

Something like:
- On page load, add listeners to state change, navigation, mutations on win-scroll
- When any of the above is detected, check if BITB was open (localstorage)
- If true, execute the open functions and ApplyPositioning

**Comment by waelmas** [comment] 2024-02-15 22:57
Just pushed a fix (changes to `pages/secondary/script.js`)
Commit: https://github.com/waelmas/frameless-bitb/commit/50d481431e37b90f4722ba4d5114d351d7b1ed92

Please open a new issue if you notice something similar again.

**Closed as completed by waelmas** 2024-02-15 22:57 UTC

**Comment by par-retest** [comment] 2024-02-16 09:48
Awesome, thanks! It fixed one of the issue, but not the KMSI one - I'll open a second issue :)
